name: build module
on: 
  workflow_dispatch:
  push:
  pull_request:

jobs:
  steve:
    runs-on: macos-latest
    steps:
      - run: brew install llvm
      - uses: actions/checkout@v3
        with:
          path: yoyo
      - uses: actions/checkout@v3
        with:
          repository: m4c0/missingno
          path: missingno
      - uses: actions/checkout@v3
        with:
          repository: m4c0/ecow
          path: ecow
      - run: |
          cd yoyo
          clang++ -I ../ecow -std=c++20 build.cpp -o build.exe
          ./build.exe
  bill:
    runs-on: windows-latest
    steps:
      - run: choco upgrade llvm -y
      - uses: actions/checkout@v3
        with:
          path: yoyo
      - uses: actions/checkout@v3
        with:
          repository: m4c0/missingno
          path: missingno
      - uses: actions/checkout@v3
        with:
          repository: m4c0/ecow
          path: ecow
      - run: |
          cd yoyo
          clang++ -I ../ecow -std=c++20 build.cpp -o build.exe
          .\build.exe
